title: salma sultana
logo: /assets/img/logo.jpg
description: Former End User Consultant, Current Software Developer, and a Master's degree holder in Data Science and Engineering.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
